version: '3'
services:
  flask:
    image: forssellm/flaskapp
    build:
      context: ./flask
      dockerfile: Dockerfile
    restart: always
    ports:
     - "5000:5000"
    depends_on:
      - redis
  celery:
    image: forssellm/flaskcelery 
    build:
      context: ./celery
      dockerfile: Dockerfile
    depends_on:
      - redis
    deploy:
      mode: replicated
      replicas: 2
  redis:
    image: redis
 